### ISSUE TITLE
pfsense router 

### ISSUE THREAD

**Issue by rstojan** [skill-collectors/incubator#12]
## What's the idea?
Learn how to setup and operate your own router.
## Why should people participate?
Consumer routers are terrible and pfsense is a free software solution to provide advanced capabilities for home labbers that can be leveraged in other home lab projects (VLAN's, IPS, traffic monitoring, DHCP, Dynamic DNS, etc.).
## What would it mean to lead?
Coordinating meetings. Lead the group through several phases including software and possible hardware implementations. 
## What would it mean to participate?
Learn more about routing and how that can help your other home lab projects with low cost hardware and free software.
## Outcome
Be able to deploy and operate a pfsense router.

**Comment by dave-burke** [comment]
What kind of hardware is available for this kind of thing? I would think that you'd want

- Something small like a commercial home router
- Something with at least two network interfaces (1 WAN and 1 LAN)
- Something with multiple physical ports on the lan interface (or ideally multiple logical lan interfaces--one per physical port).
- Ideally the ability to host a WIFI network

**Comment by rstojan** [comment]
You can go several different routes depending on your skill level, needs, and budget. However, I would probably keep WiFi Access Points separate if possible (provides more flexibility for software and hardware).

1. Build something from scratch (most fun IMHO; lots of compute power for heavy VPN traffic; high cost)
2. Re-purpose an old PC and add any extra network cards as needed (cheaper, good use of an old PC)
3. Buy a pre-built solution from someone (small and low power, possibly get support, weak ARM CPU's generally struggle with large VPN traffic workloads, cost varies).
