### ISSUE TITLE
Plex media server

### ISSUE THREAD

**Issue by rstojan** [skill-collectors/incubator#13]
## What's the idea?
Learn how to build, deploy, and operate a [Plex media server](https://www.plex.tv/).
## Why should people participate?
Plex is a free (core features) media server that can serve media including TVShows, Movies, Podcasts, and lots of other things. You can host your own media library and use the Plex apps to consume that media on a wide variety of devices (smartphones, PC, smart TV's, Roku, etc.)

This is very useful for having a "production" type service in your homelab that provides a useful service to family and friends. 
## What would it mean to lead?
Coordinating meetings. Leading the group through an example deployment on either Docker, locally hosted VM, or a virtual private server (VPS). 
## What would it mean to participate?
Learn more about self-hosting a media server.
## Outcome
Have a media server that your friends and family can consume media you host.

**Comment by dave-burke** [comment]
If anyone is interested, the configuration for my Plex server [is in](https://github.com/dave-burke/ansible-playbook/tree/master/roles/plex) my ansible repo.

**Comment by rstojan** [comment]
I can lead this project.

**Comment by ajoberstar** [comment]
Hey @rstojan, curious if you already met for this project or not. Wanted to make sure the status was up to date.

**Comment by rstojan** [comment]
Hi @ajoberstar, yeap we met about a month ago.
