### ISSUE TITLE
Jitsi Meet Server

### ISSUE THREAD

**Issue by dave-burke** [skill-collectors/incubator#26]
## What's the idea?

Walk through creating a Jitsi Meet server, and have one that the club can use to host meetings. Jitsi is a free, open source, and end-to-end encrypted video chat service with a low barrier to entry (works via Web RTC in the browser, and there are mobile applications available). It's available publicly at https://meet.jit.si, but can also be self-hosted. This project would be to create a self-hosted instance.

## Why should people participate?

Everyone is using video conferencing to keep in touch these days, and it would be good for the club to have our own solution.

## What would it mean to lead?

Schedule a time to do the work. Invite all interested members. Coordinate a discussion about implementation details. Lead the working session.

## What would it mean to participate?

Join the working session. Either to observe, troubleshoot, or work on your own installation side-by-side.

Help choose whether we use the [vanilla installlation](https://github.com/jitsi/jitsi-meet) or the [dockerized](https://github.com/jitsi/docker-jitsi-meet) installation, and whether we'd like to host on AWS or Digital Ocean.

## Outcome

The club will have a canonical Jitsi Meet server that we can use for club meetings, and members can build their own personal Jitsi Meet servers.

**Comment by JonF-864** [comment]
I'm interested in either install option.

**Comment by SavageSpaceLion** [comment]
I want to do the Jitsi docker installation on AWS
