### ISSUE TITLE
Weather app

### ISSUE THREAD

**Issue by dave-burke** [skill-collectors/incubator#33]
## What's the idea?

Build a weather app that can be used on a mobile device. My personal desire is to replace Dark Sky, which Apple recently [killed](https://www.wired.com/story/apple-buys-dark-sky/) on Android, with an open source (GPL) alternative.

I envision the app being a web app built with Vue and deployed either as a [PWA](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps) or as a native app via something like [Vue Native](https://vue-native.io/).

The project should use publicly available APIs, so it shouldn't need its own backend.

This is a possible duplicate of #6.

#### Required Features

- User configurable location that persists across page loads
- Radar showing past/future animation
- Hourly weather at least for today/tomorrow
- Daily high/low/precipitation for 7-10 days

#### Bonus features

- Detect location via GPS
- Store multiple locations
- Alerts for upcoming rain / storms

#### Open questions:

- What APIs are available? Are any of them good and free at the same time?
- What, if any, UXP framework should we use? e.g. Vuetify, bootstrap-vue, other?

## Why should people participate?

This is a great opportunity to learn about:

- Vue JS
- Progressive web applications ("offline first" apps that can be "installed" and act like native apps in Android/iOS).
- Packaging web apps as native apps
- Using browser local storage
- UI testing (likely via Cypress)

I'd also like to try setting up CI/CD via GitHub actions.

## What would it mean to lead?

Dave Burke will lead this project. He will schedule participant meetings to finalize the project workflow, technology stack, and the API we will use.

Dave will also provide any hosting (likely just an S3 bucket).

## What would it mean to participate?

We will need developers, but would also welcome people that want to work on design/UXP, testing, or security.

I'd imagine we'll use something like Trello or a GitHub project board to track the work. Once we have the tasks defined, people should be able to work on things on their own time and create PRs. We'll probably have regular meetings to keep in sync, maybe once a week?

Example tasks:

- Create a service that takes a location as input and loads the data from the chosen weather API
- Build a component to display the weather data for a single hour (to be used in a parent list component)
- Using the search field component and location service built in previous tasks, create a page for choosing the user's current location.

## Outcome

A weather app can be used on Android and iOS.

**Comment by mjp2233** [comment]
@

**Comment by bburggraff** [comment]
This sounds great!

 

One downside with using Cypress is that it does not support native app testing. If people would be willing, I've really wanted to try using https://codecept.io/. It looks to be incredibly flexible, and I really like the mocking capabilities, which would be ideal in this type of scenario where the predominate data infrastructure would be external services.

 

Regarding weather APIs, it seems like the NWS offers a free one: https://www.weather.gov/documentation/services-web-api#

There's a handful of other APIs that seem really cool (like https://openweathermap.org/api), but they all seem to have a tiered price structure around them.

 

Also, it might be worthwhile to checkout https://storybook.js.org/ so that we can breakup front-end development. Docker might be an interesting consideration too..

**Comment by dave-burke** [comment]
@bburggraff The only reason I suggested Cypress is that it's one of the [supported plugins](https://cli.vuejs.org/core-plugins/e2e-cypress.html) for the Vue CLI. I tried the other one, [Nightwatch](https://nightwatchjs.org/), and it didn't really click with me. It looks like Codecept [has a Vue plugin](https://codecept.io/vue/) so I'm all for it. I'm also not generally against setting things up by hand without the help of the CLI and plugins, but for this project I'd like to minimize "project setup" busywork in favor of getting down to the business of coding.

Storybook is actually on my personal backlog of things to check out, so I'd love to try it here. Maybe you could demo it at some point?

I was also looking at weather.gov as a possible fully free choice. I'm actually wondering if we can design a pluggable architecture where we can support multiple backend APIs with user supplied API keys. It's not as simple for the user, but I'm not trying to make a mass market app, just something I can use. We can also default to something so it works out of the box for someone that doesn't want to choose an API or get and configure a key.

**Comment by bburggraff** [comment]
@dave-burke similarly, storybook is on my list of things to try, so I'm by no means an expert on it. More so, it seems like it could be a way to break out little chunks for people to work on. 

Any ETA on a kickoff? I'm itching for a new project 😄

**Comment by dave-burke** [comment]
@bburggraff I was going to send something out this weekend. The invite will include some optional questions about what people prefer for the tech stack (like whether to use typescript or a css framework, and how we should communicate), so you'll have a little to keep you busy 😃 .

**Comment by WayneGreeley** [comment]
https://www.youtube.com/watch?v=JLc-hWsPTUY

**Comment by mjp2233** [comment]
If we're still looking for a weather API, here's a list of options. https://github.com/public-apis/public-apis#weather

**Comment by formerbee** [comment]
I'd be a fan of the weather.gov option!

**Comment by dave-burke** [comment]
Closing because this project is initiated.
