### ISSUE TITLE
"Eloquent JavaScript" book club

### ISSUE THREAD

**Issue by dave-burke** [skill-collectors/incubator#4]
## What's the idea?

A book club to read [Eloquent JavaScript](https://eloquentjavascript.net/index.html) (available to read at that link **for FREE** or [on Amazon](https://www.amazon.com/Eloquent-JavaScript-3rd-Introduction-Programming/dp/1593279507) if you prefer).

## Why should people participate?

*Eloquent JavaScript* [is](https://www.goodreads.com/list/show/10757.Best_JavaScript_Books) [frequently](https://hackr.io/blog/javascript-books) [listed](https://reactgo.com/best-javascript-books/) [as](https://medium.com/level-up-web/best-javascript-books-in-2017-72bf39d0ca73) a top resource for learning JavaScript. The book describes itself as an introduction to programming full-stop, so it should be approachable for people new to JavaScript or coding in general.

I've been wanting to read it for a long time. I think it would be useful for people totally new to programming, people new to JavaScript, or JavaScript developers who want to improve their skills and learn best practices.

## What would it mean to lead?

Take the lead in scheduling discussion meetings among the people reading the book, establishing a discussion format, and either lead the discussions or establish a rotation for group members to lead.

## What would it mean to participate?

Read sections of the book in time for the next group meeting (e.g. 1 chapter a week). The book club members should agree among themselves how often to meet and how much to read between meetings.

## Outcome

Everyone in the group has read the book. At the end it would be nice to take time at a large-group meeting to share what the book club members learned.

**Comment by dave-burke** [comment]
Sam volunteered to lead this group.

**Comment by ajoberstar** [comment]
Can change this, but made [a repo](https://github.com/skill-collectors/eloquent-javascript) where people can share solutions to the exercises.

**Comment by jfridgen** [comment]
Let me know if there's ever a Round 2 of this book club.  Would love to participate.
