### ISSUE TITLE
Open Source Discussion 

### ISSUE THREAD

**Issue by formerbee** [skill-collectors/incubator#48]
## What's the idea?

Discuss some of the topics bubbling up around Open Source in the wake of the log4j issues.

## Why should people participate?

Generate ideas and actions people can take to contribute to or support open source projects in different ways.

## What would it mean to lead?

Act as a facilitator - possibly coming up with questions or examples just in case people need prompts.

## What would it mean to participate?

Openness to learn and listen and share knowledge.

## Outcome

Possibly a list of ideas to share with others.

**Comment by dave-burke** [comment]
@onebelatedbumblebee Ditto for this one
