### ISSUE TITLE
Discussion Topic - Software Bill Of Materials (SBOM)

### ISSUE THREAD

**Issue by formerbee** [skill-collectors/incubator#49]
## What's the idea?

Talk about the concept of a software bill of materials; look at some examples; share experiences.

## Why should people participate?

Information sharing 

## What would it mean to lead?

Pull together the examples to share; come up some discussion questions if needed.

## What would it mean to participate?

Show up to learn or to share examples.

## Outcome

Increased knowledge and awareness on this topic.

**Comment by dave-burke** [comment]
@onebelatedbumblebee Hey! I am just seeing this now. I think it's an interesting idea. Would you be interested in doing this for the June or July meeting?

**Comment by formerbee** [comment]
Ah, great, thank you! I will need to pass on facilitating for now - this was more for trying to toss a couple of ideas out here to see if anyone would be interested in picking them up? I would be interested in attending though.
