### ISSUE TITLE
Request to join org

### ISSUE THREAD

**Issue by austinwhite** [skill-collectors/incubator#50]
Hi, I'm Austin. I found this group while looking through some PR's in the 'basic-computer-games' repo.

**Comment by dave-burke** [comment]
Hi @austinwhite Thanks for your interest! I'm sorry that the README doesn't really explain it very well, but this is a closed group for people who work together at the same company.

**Comment by austinwhite** [comment]
@dave-burke No worries. Admittedly, I didn't spend much time reading the README. Take care!
