### ISSUE TITLE
Request to join org

### ISSUE THREAD

**Issue by DA-Mike** [skill-collectors/incubator#52]
Please add me to the GitHub organization, thanks!

**Comment by dave-burke** [comment]
Hey! While the Guesstimator app is open to all contributors, the org is a closed group for people who work together at the same company. I'm sorry that the README doesn't really explain that.

**Comment by DA-Mike** [comment]
Hey Dave, no worries, you have an interesting group here with great goals. I'd like to keep contributing if that's ok... just think of me as the unpaid Jr. dev  ;)

**Comment by dave-burke** [comment]
Please do keep contributing! The club is for employees, but nothing here is part of our actual work. I updated the README to be more transparent, so hopefully that clears things up.
