### ISSUE TITLE
Request to join org

### ISSUE THREAD

**Issue by gretaelliott7** [skill-collectors/incubator#53]
Hello! I recently started here at Securian, I work on the FinOps team in the CCoE as a Cloud Financial Analyst. I just graduated from the University of Minnesota with my degree in Comp Sci and would love to keep my skills sharp and Rob Zelada forwarded me to this community!

**Comment by dave-burke** [comment]
Hey, welcome to the group! I'll send you an email with info about our monthly meetings and a link to our internal whiteboard. Most of what we do happens at those meetings, but this org also exists for anyone who wants to collaborate on coding projects.

If that interests you, the most active project (mostly just me at the moment, ha) is the [Guesstimator](https://github.com/skill-collectors/guesstimator) (a web app for pointing agile stories). See the [developer documentation](https://skill-collectors.github.io/guesstimator/) and the [project task board](https://github.com/orgs/skill-collectors/projects/1/views/1) for details.

We also have a [weather app](https://github.com/skill-collectors/weather-app) that isn't being actively worked on, but certainly has room for updates and new features if you wanted.
