### ISSUE TITLE
Raspberry Pi project

### ISSUE THREAD

**Issue by dave-burke** [skill-collectors/incubator#8]
## What's the idea?

Learn how to solve problems using [Raspberry Pi](https://www.raspberrypi.org/) hardware.

## Why should people participate?

Learn how to use the hardware. Connect our software experience to hardware that we can customize.

## What would it mean to lead?

Coordinating meetings. Getting Things **Done**. Coordinating how to get Raspberry Pi devices. Setting direction and getting consensus. Lead the group on choosing a project.

## What would it mean to participate?

Learn more. Help the group choose a specific project. Help other group members. Solve problems. Have fun.

**Comment by rstojan** [comment]
I use a raspberry pi in my homelab to run BIND9 for my own internal DNS needs (manage my own domains, add SRV records for FreeIPA auto-detection, etc.). A pi-hole project might be cool, less intimidating than BIND, and useful for most people (blocking bad sites on a DNS level).

**Comment by dave-burke** [comment]
👍 for [pi-hole](https://pi-hole.net/)

**Comment by dave-burke** [comment]
[NynphCast](https://github.com/MayaPosch/NymphCast/) could be a cool project, too.

It basically turns your Raspberry Pi into a Chromecast-like device.

**Comment by bwitbeck** [comment]
Related to this project, if anyone wants to learn Arduino I picked up the Elegoo (offbrand arduino, uses arduino IDE and code) and am going through their labs. We could coordinate in some evenings to go through labs together in Zoom.

This is what I picked up: https://www.amazon.com/ELEGOO-Complete-Ultimate-Tutorial-Compatible/dp/B01EWNUUUA/

**Comment by dave-burke** [comment]
Yet another Pi project is [RetroPie](https://retropie.org.uk/) which makes your Raspberry Pi a retro video game emulator (for tons of platforms--see [RetroArch](https://www.retroarch.com/)).
